### ISSUE TITLE
Algorithms under algorithms/greedy/huffamn.py are broken

### ISSUE THREAD

**Issue by nbro** [nbro/ands#6]
Since I've changed something in the interface of the HeapNode class, I realized that the code under `huffamn.py` won't work anymore. 

Removed temporarily `huffman.py`.

I should have started this project using maybe a _test-driven development_, but I was not aware at the time of all of these development processes, and I didn't have much time to do it in that way, anyway.

**Comment by dossan** [comment]
Removed temporarily `huffman.py`... it will be inserted as soon as this bug is fixed...

**Comment by nbro** [comment]
`huffman.py` was removed from this project, so this problem can be considered solved.

In the future it could be added again, but I will make sure that it's tested in order to reduce the probability of having bugs.
